eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8184
spring:
  application:
    name: service-customer
management:
  endpoints:
    web:
      exposure:
        include: "*"

