spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: http://192.168.0.17:8184/
          predicates:
            - Path=/customer/**
        - id: service-product
          uri: http://192.168.0.17:8182/
          predicates:
            - Path=/product/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.17:8761/eureka/
server:
  port: 8080