eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.17:8761/eureka/
server:
  port: 8184
spring:
  application:
    name: service-customer
  data:
    mongodb:
      host: 192.168.0.17
      port: 27017

