eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
spring:
  application:
    name: service-manage
microservice:
  web:
    customer: http://service-customer/customer

resilience4j:
  circuitbreaker:
    configs:
      default:
	registerHealthIndicator: true
        sliding-window-size: 8
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3s
    instances:
      manage:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      manage:
        base-config: default
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always