eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
spring:
  application:
    name: service-manage
microservice:
  web:
    customer: http://service-customer/customer
